 SELECT drop_table_if_exists ('domaine',false); CREATE TABLE domaine (   theme_id character varying(256) NOT NULL,   theme_libelle character varying(256) NOT NULL,   domaine_id character varying(256) NOT NULL,   domaine_libelle character varying(256) NOT NULL )  WITH OIDS; 
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('01_00_00_00', 'Raster, Prise de vue', '01_01_00_00', 'Scan');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('01_00_00_00', 'Raster, Prise de vue', '01_02_00_00', 'Ortho-Photo');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('01_00_00_00', 'Raster, Prise de vue', '01_03_00_00', 'Autres prises de vue');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('03_00_00_00', 'Urbanisme et cartes à petite echelle', '03_01_00_00', 'Limites administratives et cartes à petites echelle');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('03_00_00_00', 'Urbanisme et cartes à petite echelle', '03_02_00_00', 'Document d urbanisme');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('03_00_00_00', 'Urbanisme et cartes à petite echelle', '03_03_00_00', 'Cadastre');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('05_00_00_00', 'Réseau de Transport de personnes / déplacement', '05_01_00_00', 'Referentiel Voirie filaire / Adresse');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('05_00_00_00', 'Réseau de Transport de personnes / déplacement', '05_02_00_00', 'Transport en commun');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('05_00_00_00', 'Réseau de Transport de personnes / déplacement', '05_03_00_00', '2 roues');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('05_00_00_00', 'Réseau de Transport de personnes / déplacement', '05_04_00_00', 'Cheminement pieton et PMR');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('07_00_00_00', 'Voirie', '07_01_00_00', 'Classement / gestion');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('07_00_00_00', 'Voirie', '07_02_00_00', 'Chaussée / accotement');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('07_00_00_00', 'Voirie', '07_03_00_00', 'Référentiel Voirie - Adresse');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('09_00_00_00', 'Bâti', '09_01_00_00', 'Objet surfacique bati');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('09_00_00_00', 'Bâti', '09_02_00_00', 'Cloture / Element de séparation (objet linéaire)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('09_00_00_00', 'Bâti', '09_03_00_00', 'Seuil, Entrée');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('11_00_00_00', 'Réseau de Transport Eau et Energie', '11_01_00_00', 'Eau potable');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('11_00_00_00', 'Réseau de Transport Eau et Energie', '11_02_00_00', 'Gaz');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('11_00_00_00', 'Réseau de Transport Eau et Energie', '11_03_00_00', 'Electricité (RTE = Réseau de Transport d électricité)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('12_00_00_00', 'Réseau chauffage urbain', '12_01_00_00', 'Réseau chauffage urbain');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('13_00_00_00', 'Reseau de Distribution', '13_01_00_00', 'Eau potable');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('13_00_00_00', 'Reseau de Distribution', '13_02_00_00', 'Gaz');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('13_00_00_00', 'Reseau de Distribution', '13_03_00_00', 'Electricité');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('13_00_00_00', 'Reseau de Distribution', '13_04_00_00', 'Eclairage public');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('15_00_00_00', 'Reseau de Transport d information', '15_01_00_00', 'Réseau Ville de La Rochelle');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('15_00_00_00', 'Reseau de Transport d information', '15_02_00_00', 'Réseau opérateur');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('17_00_00_00', 'Reseau en attente', '17_01_00_00', 'Fourreau en attente - objet linéaire');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('17_00_00_00', 'Reseau en attente', '17_02_00_00', 'Fourreau en attente - objet ponctuel');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('19_00_00_00', 'Réseau de Collecte', '19_01_00_00', 'Réseau d assainissement pluvial');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('19_00_00_00', 'Réseau de Collecte', '19_02_00_00', 'Réseau d assainissement eaux usées');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('21_00_00_00', 'Signalisation lumineuse', '21_01_00_00', 'Information parking - Panneau à messages variables (PMV)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('21_00_00_00', 'Signalisation lumineuse', '21_02_00_00', 'Feu tricolore - Feu et signal lumineux (R11 à R24)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('23_00_00_00', 'Signalisation verticale', '23_01_00_00', 'Signalisation verticale de police');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('23_00_00_00', 'Signalisation verticale', '23_02_00_00', 'Signalisation verticale de direction');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('23_00_00_00', 'Signalisation verticale', '23_03_00_00', 'Autres types de signal routier');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_01_00_00', 'Lignes longitudinales axiales');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_02_00_00', 'Lignes continues délimitant le Terre Plein Central, les ilots ou certains couloirs réservés');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_03_00_00', 'Lignes longitudinales de rives ou de délimitation de certaines voies');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_04_00_00', 'Présignalisation des points singuliers');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_05_00_00', 'Lignes Transversales');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_06_00_00', 'Passages pour piétons');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_07_00_00', 'Marques de ralentisseur de type dos-d âne');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_08_00_00', 'Marques relatives aux transports en commun');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_09_00_00', 'Marques relatives au stationnement');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('25_00_00_00', 'Signalisation horizontale', '25_10_00_00', 'Marques pour voies cyclables');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('27_00_00_00', 'Stationnement', '27_01_00_00', 'Zone de stationnement (plusieurs emplacements)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('27_00_00_00', 'Stationnement', '27_02_00_00', 'Emplacement de stationnement');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('29_00_00_00', 'Espaces verts', '29_01_00_00', 'Typologie Espaces Verts');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('29_00_00_00', 'Espaces verts', '29_02_00_00', 'Objets topographiques espaces verts (necessitant une précision décimétrique)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('29_00_00_00', 'Espaces verts', '29_03_00_00', 'Espaces verts Objets topographiques espaces verts (necessitant une précision métrique)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('29_00_00_00', 'Espaces verts', '29_04_00_00', 'Gestion');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_01_00_00', 'Stationnement');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_02_00_00', 'Propreté urbaine');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_03_00_00', 'Transport');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_04_00_00', 'Affichage');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_05_00_00', 'Espaces Verts');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_06_00_00', 'Sécurité');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('31_00_00_00', 'Mobilier urbain', '31_07_00_00', 'Services (souvent externe à la ville de La Rochelle)');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('33_00_00_00', 'Geodesie, Points de référence et Habillage', '33_01_00_00', 'Géodésie');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('33_00_00_00', 'Geodesie, Points de référence et Habillage', '33_02_00_00', 'Points de référence');
INSERT INTO domaine (theme_id, theme_libelle, domaine_id, domaine_libelle) VALUES ('33_00_00_00', 'Geodesie, Points de référence et Habillage', '33_03_00_00', 'Habillage');
 VACUUM ANALYSE domaine; 
