<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2013 rel. 2 sp1 (x64) (http://www.altova.com)-->
<pcrs:FeatureCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:pcrs="http://localhost/pcrs" xmlns:gml="http://www.opengis.net/gml" xsi:schemaLocation="http://localhost/pcrs EmprisePublicationPCRS.xsd">
	<gml:boundedBy>
		<gml:Envelope srsName="EPSG:3948">
			<gml:lowerCorner>2050979.054 7273982.335408184</gml:lowerCorner>
			<gml:upperCorner>2051723.089 7274506.781</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
	<featureMember>
		<EmprisePublicationPCRS gml:id="EmprisePublicationPCRS.0">
			<gml:boundedBy>
				<gml:Envelope srsName="EPSG:3948">
					<gml:lowerCorner>2050979.054 7273982.335408184</gml:lowerCorner>
					<gml:upperCorner>2051723.089 7274506.781</gml:upperCorner>
				</gml:Envelope>
			</gml:boundedBy>
			<geometrie>
				<gml:Polygon gml:id="EmprisePublicationPCRS.geom.0" srsName="EPSG:3948">
					<gml:exterior>
						<gml:LinearRing>
							<gml:coordinates>2051681.367702676,7273982.3354081837 2051084.047,7273984.409 2050982.858,7273985.078 2050979.054,7273993.495 2050982.987,7274316.365 2050989.834,7274427.423 2050991.326,7274436.773 2051001.8609540344,7274464.8494248213 2051106.2674284296,7274485.0386759816 2051164.7448333399,7274493.8245426938 2051196.71,7274497.683 2051266.587,7274503.191 2051298.11,7274504.538 2051344.64,7274506.452 2051400.064,7274506.781 2051418.467,7274505.988 2051505.566,7274494.698 2051547.366,7274484.218 2051659.039,7274442.099 2051678.242,7274423.611 2051723.089,7274371.921 2051713.619,7274180.167 2051694.290208841,7274020.1531207385 2051681.367702676,7273982.3354081837</gml:coordinates>
						</gml:LinearRing>
					</gml:exterior>
				</gml:Polygon>
			</geometrie>
			<idEmprise>String</idEmprise>
			<gestionnaire>PCRS-GT3</gestionnaire>
			<datePublication>1967-08-13</datePublication>
			<gabaritPrecision>
				<typeObjet>1</typeObjet>
				<nombreEcartsToleres>5</nombreEcartsToleres>
				<seuil>10</seuil>
			</gabaritPrecision>
		</EmprisePublicationPCRS>
	</featureMember>
</pcrs:FeatureCollection>
