 SELECT drop_table_if_exists ('classe',false); CREATE TABLE classe (   domaine_id character varying(256) NOT NULL,   domaine_libelle character varying(256) NOT NULL,   classe_id character varying(256) NOT NULL,   classe_libelle character varying(256) NOT NULL )  WITH OIDS; 
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('01_01_00_00', 'Scan', '01_01_01_00', 'Scan IGN');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('01_01_00_00', 'Scan', '01_01_02_00', 'Scan Documents d urbanisme');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('01_02_00_00', 'Ortho-Photo', '01_02_01_00', 'Ortho à l echelle du département ou de l agglo');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('01_02_00_00', 'Ortho-Photo', '01_02_02_00', 'Ortho commune de La Rochelle');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('01_03_00_00', 'Autres prises de vue', '01_03_01_00', 'Autres prises de vue');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_01_00_00', 'Limites administratives et cartes à petites échelle', '03_01_01_00', 'Échelle nationale ou régionale');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_01_00_00', 'Limites administratives et cartes à petites échelle', '03_01_02_00', 'Échelle locale (département, CDA)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_01_00_00', 'Limites administratives et cartes à petites échelle', '03_01_03_00', 'Échelle communale');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_01_00', 'Schéma Directeur ou SCOT');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_02_00', 'Zonage POS ou PLU');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_03_00', 'Prescriptions, Servitudes et autres zonages');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_04_00', 'Monuments et sites classés ou inscrits');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_05_00', 'ZPPAUP');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_02_00_00', 'Urbanisme Document d urbanisme', '03_02_06_00', 'Plan de sauvegarde et de mise en valeur');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_03_00_00', 'Urbanisme Cadastre', '03_03_01_00', 'Cadastre Hors La Rochelle');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('03_03_00_00', 'Urbanisme Cadastre', '03_03_02_00', 'Cadastre La Rochelle');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_01_00_00', 'Réseau de Transport de personnes / déplacement Référentiel Voirie filaire / Adresse', '05_01_01_00', 'Surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_01_00_00', 'Réseau de Transport de personnes / déplacement Référentiel Voirie filaire / Adresse', '05_01_02_00', 'Voirie filaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_01_00_00', 'Réseau de Transport de personnes / déplacement Référentiel Voirie filaire / Adresse', '05_01_03_00', 'Carrefour');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_01_00_00', 'Réseau de Transport de personnes / déplacement Référentiel Voirie filaire / Adresse', '05_01_04_00', 'Point adresse postale');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_01_00_00', 'Réseau de Transport de personnes / déplacement Référentiel Voirie filaire / Adresse', '05_01_05_00', 'Photos');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_02_00_00', 'Réseau de Transport de personnes / déplacement Transport en commun', '05_02_01_00', 'Station transport en commun');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_02_00_00', 'Réseau de Transport de personnes / déplacement Transport en commun', '05_02_02_00', 'Ligne transport en commun');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_02_00_00', 'Réseau de Transport de personnes / déplacement Transport en commun', '05_02_03_00', 'Voie réservée taxi et transport en commun');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_03_00_00', 'Réseau de Transport de personnes / déplacement 2 roues', '05_03_01_00', 'Bande cyclable');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_03_00_00', 'Réseau de Transport de personnes / déplacement 2 roues', '05_03_02_00', 'Piste cyclable');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_03_00_00', 'Réseau de Transport de personnes / déplacement 2 roues', '05_03_03_00', 'Autre élément déplacement 2 roues');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_04_00_00', 'Réseau de Transport de personnes / déplacement Cheminement piéton et PMR', '05_04_01_00', 'Voie piétonne');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_04_00_00', 'Réseau de Transport de personnes / déplacement Cheminement piéton et PMR', '05_04_02_00', 'Passage souterrain');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('05_04_00_00', 'Réseau de Transport de personnes / déplacement Cheminement piéton et PMR', '05_04_03_00', 'Pont, passerelle piétonne');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_01_00_00', 'Voirie Classement / gestion', '07_01_01_00', 'Gestion Conseil Général');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_01_00_00', 'Voirie Classement / gestion', '07_01_02_00', 'Gestion CDA');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_01_00_00', 'Voirie Classement / gestion', '07_01_03_00', 'Gestion Ville');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_02_00_00', 'Voirie Chaussée / accotement', '07_02_01_00', 'Objets surfaciques (chaussée, accotement, revêtement, )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_02_00_00', 'Voirie Chaussée / accotement', '07_02_02_00', 'Objets linéaires (limite de chaussée, limite de revêtement, bordure, fossé, )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('07_02_00_00', 'Voirie Chaussée / accotement', '07_02_03_00', 'Objets ponctuels ( )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_01_00', 'Emprise bâtiment');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_02_00', 'Ouvrage d art, pont, passerelle');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_03_00', 'Bloc béton, pilier');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_04_00', 'Statue ou monument');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_05_00', 'Limite surface taxée');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_06_00', 'Devanture');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_07_00', 'Ruine');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_08_00', 'Mur cyclopéen');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_01_00_00', 'Bâti Objet surfacique bâti', '09_01_09_00', 'Tombe');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_01_00', 'Limite de propriété (façade<->domaine public)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_02_00', 'Limite séparative entre deux propriétés');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_03_00', 'Limite de bâtiment / façade');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_04_00', 'Proéminence d un bâtiment par rapport à sa façade levée');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_05_00', 'Mur');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_06_00', 'Mur de soutènement');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_07_00', 'Limite épaisseur mur (deuxième trait)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_08_00', 'Clôture');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_02_00_00', 'Bâti Clôture / Élément de séparation (objet linéaire)', '09_02_09_00', 'Préau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('09_03_00_00', 'Bâti Seuil, Entrée', '09_03_01_00', 'Bâti Seuil, Entrée');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_01_00_00', 'Réseau de Transport Eau et Énergie Eau potable', '11_01_01_00', 'Conduite de transfert (feeder)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_01_00_00', 'Réseau de Transport Eau et Énergie Eau potable', '11_01_02_00', 'Ouvrage d adduction (notion d eau brute, d aqueduc)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_02_00_00', 'Réseau de Transport Eau et Énergie Gaz', '11_02_01_00', 'GDF haute pression transport');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_02_00_00', 'Réseau de Transport Eau et Énergie Gaz', '11_02_02_00', 'GDF moyenne pression transport');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_02_00_00', 'Réseau de Transport Eau et Énergie Gaz', '11_02_03_00', 'Société X');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_02_00_00', 'Réseau de Transport Eau et Énergie Gaz', '11_02_04_00', 'Société Y');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_03_00_00', 'Réseau de Transport Eau et Énergie Électricité (RTE = Réseau de Transport d électricité)', '11_03_01_00', 'HTB (U > 75 kV)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('11_03_00_00', 'Réseau de Transport Eau et Énergie Électricité (RTE = Réseau de Transport d électricité)', '11_03_02_00', 'HTA (1500 < U < 75 kV)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('12_01_00_00', 'Réseau de distribution chauffage urbain', '12_01_02_00', 'Objet linéaire du réseau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('12_01_00_00', 'Réseau de distribution chauffage urbain', '12_01_03_00', 'Objet ponctuel du réseau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_01_00_00', 'Réseau de Distribution Eau potable', '13_01_01_00', 'Objet surfacique du réseau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_01_00_00', 'Réseau de Distribution Eau potable', '13_01_02_00', 'Objet linéaire du réseau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_01_00_00', 'Réseau de Distribution Eau potable', '13_01_03_00', 'Objet ponctuel du réseau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_01_00_00', 'Réseau de Distribution Eau potable', '13_01_04_00', 'Autre élément');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_02_00_00', 'Réseau de Distribution Gaz', '13_02_01_00', 'GDF basse pression distribution');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_02_00_00', 'Réseau de Distribution Gaz', '13_02_02_00', 'Vanne Gaz');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_02_00_00', 'Réseau de Distribution Gaz', '13_02_03_00', 'Branchement individuel GDF');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_02_00_00', 'Réseau de Distribution Gaz', '13_02_04_00', 'Autre élément');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_02_00_00', 'Réseau de Distribution Gaz', '13_02_05_00', 'Gaz basse pression distribution Société Y');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_01_00', 'Objet surfacique (réseau de distribution Électricité)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_02_00', 'Poste EDF');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_03_00', 'Objet linéaire (HTA (1500 < U < 75 kV))');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_04_00', 'Objet linéaire (BTB (750 < U < 1500 V))');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_05_00', 'Objet linéaire (BTA (120 < U < 750 V))');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_03_00_00', 'Réseau de Distribution Électricité', '13_03_15_00', 'Objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_04_00_00', 'Réseau de Distribution Éclairage public', '13_04_01_00', 'Objet surfacique (Éclairage public)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_04_00_00', 'Réseau de Distribution Éclairage public', '13_04_02_00', 'Objet Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('13_04_00_00', 'Réseau de Distribution Éclairage public', '13_04_03_00', 'Objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_01_00_00', 'Réseau de Transport d information Réseau Ville de La Rochelle', '15_01_01_00', 'Poste de Contrôle d Accès (PCA)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_01_00_00', 'Réseau de Transport d information Réseau Ville de La Rochelle', '15_01_02_00', 'Regard comptage routier');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_01_00_00', 'Réseau de Transport d information Réseau Ville de La Rochelle', '15_01_03_00', 'Réseau DSI');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_02_00_00', 'Réseau de Transport d information Réseau opérateur', '15_02_01_00', 'Objet surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_02_00_00', 'Réseau de Transport d information Réseau opérateur', '15_02_02_00', 'Objet Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('15_02_00_00', 'Réseau de Transport d information Réseau opérateur', '15_02_03_00', 'Objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('17_01_00_00', 'Fourreau en attente - objet linéaire', '17_01_01_00', 'Fourreau en attente - objet linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('17_02_00_00', 'Fourreau en attente - objet ponctuel', '17_02_01_00', 'Fourreau en attente - objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_01_00_00', 'Réseau de Collecte Réseau d assainissement pluvial', '19_01_01_00', 'Objet surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_01_00_00', 'Réseau de Collecte Réseau d assainissement pluvial', '19_01_02_00', 'Objet Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_01_00_00', 'Réseau de Collecte Réseau d assainissement pluvial', '19_01_03_00', 'Objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_02_00_00', 'Réseau de Collecte Réseau d assainissement eaux usées', '19_02_01_00', 'Objet surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_02_00_00', 'Réseau de Collecte Réseau d assainissement eaux usées', '19_02_02_00', 'Objet Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('19_02_00_00', 'Réseau de Collecte Réseau d assainissement eaux usées', '19_02_03_00', 'Objet ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('21_01_00_00', 'Signalisation lumineuse Information parking - Panneau à messages variables (PMV)', '21_01_01_00', 'Panneau à messages variables (PMV)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('21_02_00_00', 'Signalisation lumineuse Feu tricolore - Feu et signal lumineux (R11 à R24)', '21_02_01_00', 'Armoire de commande Signalisation Tricolore');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('21_02_00_00', 'Signalisation lumineuse Feu tricolore - Feu et signal lumineux (R11 à R24)', '21_02_02_00', 'Regard Technique Signalisation Tricolore');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('21_02_00_00', 'Signalisation lumineuse Feu tricolore - Feu et signal lumineux (R11 à R24)', '21_02_03_00', 'Feu et signal lumineux (R11 à R24) accroché à un point de référence (support ou applique)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_01_00', 'Panneaux de danger (A1a à A24)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_02_00', 'Panneaux d intersection et de priorité (AB1 à AB25)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_03_00', 'Panneaux de prescription (B0 à B51)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_04_00', 'Panneaux d indication (C1a à CE50)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_05_00', 'Panonceaux (M1 à M11b)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_06_00', 'Symboles (SE2b à SU1)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_01_00_00', 'Signalisation verticale Signalisation verticale de police', '23_01_07_00', 'Autres objets');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_01_00', 'Panneaux de direction (D21a à D79b)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_02_00', 'Panneaux de jalonnement piétonnier (Dp1a à Dp2b)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_03_00', 'Panneaux de jalonnement pour cyclistes (Dv11 à Dv61)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_04_00', 'Panneaux de localisation (E31 à EB20)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_05_00', 'Panneaux d information (H11 à H33)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_06_00', 'Idéogrammes, emblèmes ou logotypes (ID1 à ID15a41 + Logotype)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_02_00_00', 'Signalisation verticale Signalisation verticale de direction', '23_02_07_00', 'Autres objets');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_03_00_00', 'Signalisation verticale Autres types de signal routier', '23_03_01_00', 'Balises (J1 à J14b)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_03_00_00', 'Signalisation verticale Autres types de signal routier', '23_03_02_00', 'Feux de balisage et d alerte (G1 à R2d)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_03_00_00', 'Signalisation verticale Autres types de signal routier', '23_03_03_00', 'Panneaux à messages variables (PMV)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('23_03_00_00', 'Signalisation verticale Autres types de signal routier', '23_03_04_00', 'Panneaux et dispositifs de signalisation temporaire (AK2 à KR11)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_01_00_00', 'Signalisation horizontale Lignes longitudinales axiales', '25_01_01_00', 'Lignes continues (continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_01_00_00', 'Signalisation horizontale Lignes longitudinales axiales', '25_01_02_00', 'Lignes discontinues de type T1 (T1, Tp1, ou T3)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_01_00_00', 'Signalisation horizontale Lignes longitudinales axiales', '25_01_03_00', 'Lignes discontinues de type T3 (T3)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_01_00_00', 'Signalisation horizontale Lignes longitudinales axiales', '25_01_04_00', 'Lignes mixtes (T1 ou T3)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_02_00_00', 'Signalisation horizontale Lignes continues délimitant le Terre Plein Central, les îlots ou certains couloirs réservés', '25_02_01_00', 'Ligne de délimitation de terre-plein central (continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_02_00_00', 'Signalisation horizontale Lignes continues délimitant le Terre Plein Central, les îlots ou certains couloirs réservés', '25_02_02_00', 'Ligne de délimitation du contour des îlots (continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_02_00_00', 'Signalisation horizontale Lignes continues délimitant le Terre Plein Central, les îlots ou certains couloirs réservés', '25_02_03_00', 'Ligne de délimitation de certains couloirs réservés (continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_03_00_00', 'Signalisation horizontale Lignes longitudinales de rives ou de délimitation de certaines voies', '25_03_01_00', 'Lignes discontinues de type T2 (T2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_03_00_00', 'Signalisation horizontale Lignes longitudinales de rives ou de délimitation de certaines voies', '25_03_02_00', 'Lignes discontinues de type T3 (T3 ou Tp3)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_04_00_00', 'Signalisation horizontale Pré signalisation des points singuliers', '25_04_01_00', 'Ligne d annonce d une ligne continue (T3)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_04_00_00', 'Signalisation horizontale Pré signalisation des points singuliers', '25_04_02_00', 'Flèches de rabattement');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_04_00_00', 'Signalisation horizontale Pré signalisation des points singuliers', '25_04_03_00', 'Flèches directionnelles');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_05_00_00', 'Signalisation horizontale Lignes Transversales', '25_05_01_00', 'Ligne _STOP_ (continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_05_00_00', 'Signalisation horizontale Lignes Transversales', '25_05_02_00', 'Ligne _Cédez-le-passage_ (Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_05_00_00', 'Signalisation horizontale Lignes Transversales', '25_05_03_00', 'Ligne d effet des feux (Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_05_00_00', 'Signalisation horizontale Lignes Transversales', '25_05_04_00', 'Ligne de guidage en intersection Tourne à gauche à l indonésienne - carrefour en baïonnette (Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_05_00_00', 'Signalisation horizontale Lignes Transversales', '25_05_05_00', 'Ligne de début et de fin de voie cyclable (Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_06_00_00', 'Passages pour piétons', '25_06_01_00', 'Passages pour piétons');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_07_00_00', 'Marques de ralentisseur de type dos-d âne', '25_07_01_00', 'Marques de ralentisseur de type dos-d âne');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_08_00_00', 'Signalisation horizontale Marques relatives aux transports en commun', '25_08_01_00', 'Ligne marquant l emplacement d un arrêt d autobus (jaune, continue, zigzag)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_08_00_00', 'Signalisation horizontale Marques relatives aux transports en commun', '25_08_02_00', 'Franchissement des carrefours par les voies réservées (blanc, damier)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_08_00_00', 'Signalisation horizontale Marques relatives aux transports en commun', '25_08_03_00', 'Inscriptions sur les voies réservées (_BUS_)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_09_00_00', 'Signalisation horizontale Marques relatives au stationnement', '25_09_01_00', 'Ligne délimitant les places de stationnement (blanche ou bleue, Tp2 ou continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_09_00_00', 'Signalisation horizontale Marques relatives au stationnement', '25_09_02_00', 'Ligne confirmant ou indiquant l interdiction de stationner (jaune, Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_09_00_00', 'Signalisation horizontale Marques relatives au stationnement', '25_09_03_00', 'Ligne confirmant ou indiquant l interdiction de s arrêter (jaune, continue)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('25_10_00_00', 'Signalisation horizontale Marques pour voies cyclables', '25_10_01_00', 'Traversées de chaussées par les voies cyclables (Tp2)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_01_00_00', 'Stationnement Zone de stationnement (plusieurs emplacements)', '27_01_01_00', 'Contour de parking');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_01_00_00', 'Stationnement Zone de stationnement (plusieurs emplacements)', '27_01_02_00', 'Zone de livraison');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_01_00_00', 'Stationnement Zone de stationnement (plusieurs emplacements)', '27_01_03_00', 'Horodateur');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_01_00_00', 'Stationnement Zone de stationnement (plusieurs emplacements)', '27_01_04_00', 'Péage');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_01_00', 'Emplacement normal');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_02_00', 'Emplacement PMR');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_03_00', 'Emplacement Taxi');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_04_00', 'Emplacement Transporteur de fond');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_05_00', 'Emplacement Livraison');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('27_02_00_00', 'Stationnement Emplacement de stationnement', '27_02_06_00', 'Emplacement Véhicule électrique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_01_00', 'Parcs, jardins et squares');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_02_00', 'Accompagnement de voies');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_03_00', 'Accompagnement bâtiments publics');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_04_00', 'Accompagnement habitations');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_05_00', 'Accompagnement établissement industriels et commerciaux');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_06_00', 'Espaces verts établissements sociaux ou éducatifs');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_07_00', 'Sports');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_08_00', 'Cimetières');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_09_00', 'Campings');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_10_00', 'Établissements horticoles');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_11_00', 'Espaces naturels aménagés');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_12_00', 'Jardins familiaux');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_01_00_00', 'Espaces verts Typologie Espaces Verts', '29_01_13_00', 'Arbres d alignement');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_02_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision décimétrique)', '29_02_01_00', 'Surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_02_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision décimétrique)', '29_02_02_00', 'Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_02_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision décimétrique)', '29_02_03_00', 'Ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_03_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision métrique)', '29_03_01_00', 'Surfacique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_03_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision métrique)', '29_03_02_00', 'Linéaire');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_03_00_00', 'Espaces verts Objets topographiques espaces verts (nécessitant une précision métrique)', '29_03_03_00', 'Ponctuel');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_04_00_00', 'Espaces verts Gestion', '29_04_01_00', 'Espaces Verts entretien Ville La Rochelle');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_04_00_00', 'Espaces verts Gestion', '29_04_02_00', 'Espaces Verts entretien Organisme HLM');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('29_04_00_00', 'Espaces verts Gestion', '29_04_03_00', 'Espaces Verts entretien Autre organisme ou privé');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_01_00_00', 'Mobilier urbain Stationnement', '31_01_01_00', 'Horodateur');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_02_00_00', 'Mobilier urbain Propreté urbaine', '31_02_01_00', 'Corbeille');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_01_00', 'Groupe d Arceaux stationnement vélo (Parking cycle)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_02_00', 'Arceau stationnement vélo');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_03_00', 'Arceau chicane');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_04_00', 'Abribus');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_05_00', 'Poteau d arrêt de bus');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_03_00_00', 'Mobilier urbain Transport', '31_03_06_00', 'Borne Auto Plus');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_04_00_00', 'Mobilier urbain Affichage', '31_04_01_00', 'Informatif et/ou publicitaire (planimètre)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_04_00_00', 'Mobilier urbain Affichage', '31_04_02_00', 'Panneau d affichage libre');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_04_00_00', 'Mobilier urbain Affichage', '31_04_03_00', 'Fourreau pour mat de pavoisement');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_05_00_00', 'Mobilier urbain Espaces Verts', '31_05_01_00', 'Objet Surfacique (vespachien, jeu d enfants, kiosque,  )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_05_00_00', 'Mobilier urbain Espaces Verts', '31_05_02_00', 'Objet Linéaire ()');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_05_00_00', 'Mobilier urbain Espaces Verts', '31_05_03_00', 'Objet Ponctuel (Banc, Jardinière,  )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_06_00_00', 'Mobilier urbain Sécurité', '31_06_01_00', 'Objet Surfacique (Poste de Contrôle d accès,  )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_06_00_00', 'Mobilier urbain Sécurité', '31_06_02_00', 'Objet Linéaire (barrière de ville, chaîne, gabarit de hauteur, barrière levante,  )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_06_00_00', 'Mobilier urbain Sécurité', '31_06_03_00', 'Objet Ponctuel (Borne / Potelet,  )');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_07_00_00', 'Mobilier urbain Services (souvent externe à la ville de La Rochelle)', '31_07_01_00', 'Boite aux lettres');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_07_00_00', 'Mobilier urbain Services (souvent externe à la ville de La Rochelle)', '31_07_02_00', 'Cabine téléphonique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_07_00_00', 'Mobilier urbain Services (souvent externe à la ville de La Rochelle)', '31_07_03_00', 'Coffret relais de la poste');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('31_07_00_00', 'Mobilier urbain Services (souvent externe à la ville de La Rochelle)', '31_07_04_00', 'Container déchet');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_01_00_00', 'Géodésie, Points de référence et Habillage Géodésie', '33_01_01_00', 'Point géodésique');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_01_00_00', 'Géodésie, Points de référence et Habillage Géodésie', '33_01_02_00', 'Point nivellement');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_01_00_00', 'Géodésie, Points de référence et Habillage Géodésie', '33_01_03_00', 'Courbe de niveau');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_02_00_00', 'Géodésie, Points de référence et Habillage Points de référence', '33_02_01_00', 'Position géographique d un appareil de fontainerie du réseau eau potable ou gaz');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_02_00_00', 'Géodésie, Points de référence et Habillage Points de référence', '33_02_02_00', 'Position géographique d un regard ou d une plaque');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_02_00_00', 'Géodésie, Points de référence et Habillage Points de référence', '33_02_03_00', 'Position géographique d un Support (système d accrochage vertical)');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_03_00_00', 'Géodésie, Points de référence et Habillage Habillage', '33_03_01_00', 'Élément d habillage non géo-référencé');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_03_00_00', 'Géodésie, Points de référence et Habillage Habillage', '33_03_02_00', 'Élément d habillage géo-référencé');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_03_00_00', 'Géodésie, Points de référence et Habillage Habillage', '33_03_03_00', 'Texte divers non géo-référencé');
INSERT INTO classe (domaine_id, domaine_libelle, classe_id, classe_libelle) VALUES ('33_03_00_00', 'Géodésie, Points de référence et Habillage Habillage', '33_03_04_00', 'Texte divers géo-référencé');
 VACUUM ANALYSE classe; 
